# Inferential Stats - Sampling Distributions

In [1]:
import numpy as np
import scipy
import pandas as pd
from itertools import chain
from math import factorial
#---
import plotly.graph_objects as go
import plotly.io as pio
import plotly.express as px 
import plotly.figure_factory as ff
#--
pio.templates.default = 'plotly_dark'

## Probabilities 
- sets are collections of objects, objects can be categorical or numerical (other but these are focus on in healthcare). Ex.: a set can be a list of all possible complications of a new intervention, each element is a complication in the set
- subsets, union of sets (combines, no repeats), membership of a set. Complications can be in either or both sets
- coin flips, outcomes are indep events, 2 coin flips:
    - HH, HT, TH, TT  : 1/4 = 25% of outcome  :: P(HH) = 0.25, 2 Heads in a row
    - P(1+ H or 1+ T ) = 0.75 
    

### coin flip 3 times, choice = {0: Tails, 1: Heads}
- ``np.random.choice(np.array([0,1]), n, replace=True)``  n= number of times we want to choose from this set

In [2]:
coin_flip = np.random.choice(np.array([0,1]), 3, replace=True)
coin_flip

array([1, 1, 0])

In [3]:
# 3 coin flips 5 times
coin_flip = [np.random.choice(np.array([0,1]), 3, replace=True) for i in range(5)]
coin_flip

[array([1, 0, 1]),
 array([0, 1, 1]),
 array([0, 1, 1]),
 array([0, 1, 1]),
 array([0, 1, 1])]

In [4]:
# np.random.seed(12)
count = 0

for i in range(1000):
    flip_3 =sum(np.random.choice(np.array([0,1]), 3, replace=True))
    if flip_3 >0:
        count +=1
print(f'Total experiments: 1000','\n',f'Total number of Heads: {count}')

Total experiments: 1000 
 Total number of Heads: 879


In [5]:
#  Unconditional probability 
#  patients have only 1 disease of all diseases
df = pd.DataFrame({
    'Group':['A','B'],
    'HT':[0.26,0.09], # Hypertension
    'Diabetes':[0.36,0.07],
    'IDH':[0.18,0.04]
})
df.set_index('Group',inplace=True)
df

HT  Diabetes   IDH
Group                      
A      0.26      0.36  0.18
B      0.09      0.07  0.04

In [6]:
# total relative frequences in row 1

#  marginal probability
ax1 = df.sum(axis=1)  
print('Probability across row 1: \n',ax1,'\n')
# unconditional probability of having diabetes is column total

ax0 = df.sum(axis=0)  # 43% regardless of which group
print('Probability down columns: \n',ax0)

Probability across row 1: 
 Group
A    0.8
B    0.2
dtype: float64 

Probability down columns: 
 HT          0.35
Diabetes    0.43
IDH         0.22
dtype: float64


### **joint probability** 
- 2 outcomes at 1 time: Group_A  **and** diabetes. == 36%

### **conditional probability** 
- likelihood of outcome given than another occured
- P( Diabetes [] group_A ) = (.36) / (.80)  == 45%

In [7]:
# Probability of diabetes given being in group A
p_A_given_B = (.36)/ (.8)
#  Probability of being in group A given diabetes disease
p_B_given_A = (.36) / (.43)
# probability of having diabetes
p_A = .43
# probability of being in group A
p_B = 0.8

### select a patient at random 
what is the probability that they have hypertension (A) **OR** are in the treatment group B? 
- P(A and B) = P(A) + P(B) -P(A and B)

In [8]:
df

HT  Diabetes   IDH
Group                      
A      0.26      0.36  0.18
B      0.09      0.07  0.04

In [9]:
# HT group column
p_HT_group = .35
# probability of treatment
p_Treatment_group_B = 0.09 + .07 + .04
# probability of HT AND group B
p_HT_Group_B = .09

# P(A and B)
P_A_and_B =  p_HT_group + p_Treatment_group_B - p_HT_Group_B
print('Probality of HT and Group B: {:.1f}%'.format(P_A_and_B*100))

Probality of HT and Group B: 46.0%


Patient at random, has **both** HT **and** in treatment group B
- P(A and B) = P( A [] B ) * P(B)
- P(A and B) = P( B [] A ) * P(A)

In [10]:
P_A_and_B = p_Treatment_group_B * p_HT_group
round(P_A_and_B,2)

0.07

## Rolling of Dice (2 of them)
- rolling 2 dice, the min and max value 

In [11]:
outcomes = []
def add2(x):
    for r in range(0,6):
        x = r+1
        outcomes.append(x)
    print("All posible outcomes:")
    print('',outcomes,'+',outcomes)

In [12]:
add2(1)

All posible outcomes:
 [1, 2, 3, 4, 5, 6] + [1, 2, 3, 4, 5, 6]


In [13]:
import random
min=1
max= 6
dice_1 = random.randint(min,max)
dice_2 = random.randint(min,max)
print(f'{dice_1} + {dice_2}')

1 + 1


All possible dice rolling outcomes

- P(X= 2) => 1/36
- P(X= 3) => 2/36
- P(X= 4) => 3/36
- P(X= 5) => 4/36
- P(X= 6) => 5/36
- P(X= 7) => 6/36
- P(X= 8) => 5/36
- P(X= 9) => 4/36
- P(X= 10) => 3/36
- P(X= 11) => 2/36
- P(X= 12) => 1/36

In [19]:
# 11 probabilities of summed values
#              #'s:  2,3,4,5,6, 7, 8,9,10,11,12
p = [i /36 for i in [1,2,3,4,5, 6, 5,4,3,2,1]] #probability of rolling that sum
print(p)
print(p[-1])

[0.027777777777777776, 0.05555555555555555, 0.08333333333333333, 0.1111111111111111, 0.1388888888888889, 0.16666666666666666, 0.1388888888888889, 0.1111111111111111, 0.08333333333333333, 0.05555555555555555, 0.027777777777777776]
0.027777777777777776


In [15]:
# probability of outcome being >= 10
# P(X >= 10) = 
p_10 = p[-3]
p_11 = p[-2]
p_12 = p[-1]

P_x10_plus = p_10 + p_11 + p_12
print('Probability of rolling 10 or higher: ',round((P_x10_plus)*100),'%')

Probability of rolling 10 or higher:  17 %


This is to test if LaTeX works for $X$ >= 10 $P \left(X \ge 10 \right) $

In [16]:
# roll dice 10_000 times
np.random.seed(3)
roll_totals = pd.DataFrame({
    'RollTotal': [np.sum(np.random.randint(1, 
                                           high=7, 
                                           size=2)).tolist() for i in range(10_000)]
})
roll_totals.head()

RollTotal
0          4
1          6
2          2
3          7
4         10

In [17]:
roll_totals.RollTotal.value_counts(normalize=True)

7     0.1699
6     0.1405
8     0.1337
5     0.1111
9     0.1047
10    0.0854
4     0.0853
11    0.0559
3     0.0554
12    0.0299
2     0.0282
Name: RollTotal, dtype: float64

In [18]:
#  sort in order 
roll_totals.RollTotal.value_counts().sort_index()

2      282
3      554
4      853
5     1111
6     1405
7     1699
8     1337
9     1047
10     854
11     559
12     299
Name: RollTotal, dtype: int64

In [22]:
# bar chart of results
px.bar(x= range(2,13),
        y= roll_totals.RollTotal.value_counts().sort_index().tolist(),
       title="Bar Chart of Rolling Dice Probabilities (10,000 rolls)",
       labels= {'x':'X Sum of 2 dice','y': 'Frequency'}).show()

## random variable Emperical Distributions 

In [34]:
#  simulate clinicl trial :
#         pseudo-random height in cm of 200 women, normal distribution
#  SciPy stats normal continuous random variables (rvs)
from scipy import stats
height = stats.norm.rvs(loc= 160, # mean
                       scale= 10, # std
                       size= 200, # N 
                       random_state= 1, # for repeating
                       )

height_distplot = ff.create_distplot([height],['Height'], 
                                     bin_size=5,
                                    colors=['rgb(0, 200, 200)'] 
                                    )
height_distplot.show() # KDE and Rugplot 

## Theoretical Distribution
- mathematical reason for continuous and discrete variables 
- **Expected value** of a random variable, the mean of that occuring if that random experiment is repeated numerous times, a weighted average

In [39]:
# random variable times its probability 
dice_probabilities = [i/36 for i in [1,2,3,4,5,6,5,4,3,2,1]]
dice_range = np.arange(2,13) * np.array(dice_probabilities)
print(dice_range)

#  Expected value
expected_value = np.sum(dice_range)
print('Expected value: ',round(expected_value))

[0.05555556 0.16666667 0.33333333 0.55555556 0.83333333 1.16666667
 1.11111111 1.         0.83333333 0.61111111 0.33333333]
Expected value:  7


## Continuous Normal Distribution (Bell Shape)

In [80]:
# stats.norm.ppf  = Percent Point Function is a 1-tail test
# returns a value marking where the 99% of data points would be in a normal dist
lower = stats.norm.ppf(0.01, loc=0, scale=1)
print(lower)
higher = stats.norm.ppf(0.99, loc=0, scale=1)
print(higher)

-2.3263478740408408
2.3263478740408408


In [87]:
# # numpy array.flatten() returns a collaped array into 1 dimension
nparr = np.array([[1,2],[3,4]])
print(nparr)

# flatten this array
nparr_flat = nparr.flatten()
print('\n',nparr_flat)

[[1 2]
 [3 4]]

 [1 2 3 4]


In [100]:
# np.linspace returns evenly spaced values [start,stop, num= N]
values = np.linspace(lower, higher, 100)

values_flatten = list(values.flatten())
print('np.linspace :',values_flatten[0:5])

# stats.norm.pdf = Probability Density Function
pdf_values = stats.norm.pdf(values)
pdf_values = list(pdf_values.flatten())
print('stats.norm.pdf: ',pdf_values[0:5])




np.linspace : [-2.3263478740408408, -2.279350947292541, -2.232354020544241, -2.1853570937959415, -2.1383601670476415]
stats.norm.pdf:  [0.02665214220345808, 0.029698495124487845, 0.03302003535669454, 0.03663206435224366, 0.04054954840560043]


In [122]:
area_fig = go.Figure()
area_fig.add_trace(go.Scatter(
    x= values_flatten,
    y= pdf_values,
    mode='lines',
    name='Standard Normal Distribution',
))

area_fig.add_trace(go.Scatter(
    x= [-1,-1],
    y= [0,0,4],
    mode='lines',
    name='Difference in Means',
   
))
area_fig.show() # suppose to have red line @ -1 line 

## Binomial Distribution
- the number of occurences of a **success** in a set number *given* a probability for a success
- only 2 elements for the variable: success and failure, each is independent of all other outcomes, probability of **failure** remains constant
- Investgate whether specific side-effects when taking a drug:
    - having a side effect = **success**
    - no side effect = **failure** 
    - assume the side effect has a 5% chance of occuring in each individual, there are 0 to 4 side effects occuring in 10 people

In [123]:
def binom(n,k,p):
    return (factorial(n) // factorial(k) // factorial(n - k)) * (p**k) * ((1-p) ** (n - k)) 

In [124]:
def binomial(n,k,p):
    n_ = (factorial(n))
    k_ = (factorial(k))
    n_min_k = (factorial(n - k))
    p_exp_k = (p**k)
    one_min_p = (1 - p)
    n_Minus_K = (n - k)
    
    return ((n_) / k_ * n_min_k) * p_exp_k * one_min_p ** n_Minus_K

calculate probability of 2 side effects among 10 people, given a probability of a side effect in any indiidual is 0.05%

In [139]:
#    (10 people, 2 side effects, probability of 1 side effect)
drug_side_efx = binom(10, 2, 0.05)
print("probability of 2 side effects n=10 :", round((drug_side_efx),4)*100,'%' )

probability of 2 side effects n=10 : 7.46 %


In [140]:
# list comprehension of probability of 0,1,2,3,4 side effects in 10 people
probs = [binom(10,k, 0.05) for k in range(5)]
probs

[0.5987369392383787,
 0.31512470486230454,
 0.07463479852001952,
 0.010475059441406248,
 0.0009648081064453125]

In [142]:
# plot the probabilities of side efefct outcomes
px.bar(x= range(5),
      y= probs,
      labels= {'x':"Number of Complications","y":"Probability"},
       title= "Drug side-effect probabilities (n = 10)"
      ).show()

Binomial Distributions calculations
- Expected Value = (number of experiments)  x  (probability of success)
- Variance = (number of experiments) x (probability of success) x (probability of failure)

## Sampling Distribution
- select 100 people at random and measure their height, calculate the mean height for these 100 people, the mean value is a statistic
- if we repeat experiment with new people, we would have new height mean, repeating this process will result in a sampling distribution

In [150]:
population_height = np.random.randint(low=140, high= 200, size=10_000)
px.histogram(x= population_height)
#  empirical uniform distribution

In [155]:
#  select 100 people but save the mean height, repeat 1000 times
#  normal distribution, central limit theorem 
mean_ht = [np.random.choice(population_height,
                           size= 100,
                           replace=False).mean() for i in range(1_000)]

px.histogram(x= mean_ht,
            labels= {'x':'Mean Height','count':'Frequency'}).show()

**Z** distribution is used to know the **std** of the variable in the population, this is rare, need large sample size to approximate the z distribution

**t** distribution is the **std** that is *unknown* in most cases, based on degree of freedom, use PPF for the t-distribution 

In [162]:
lower = stats.t.ppf(0.01, 30) # 1%, 30 people
higher = stats.t.ppf(.99, 30)
print(lower, higher)

values_t = np.linspace(lower, higher, 100)
values_t_flatten = list(values_t.flatten())
print(values_t_flatten[0:5])

px.line(x= values_t_flatten,
       y= pdf_values ,
       title='t - distribution (n= 30)').show()

-2.4572615424005706 2.4572615424005697
[-2.4572615424005706, -2.407619895079347, -2.3579782477581235, -2.3083366004368995, -2.258694953115676]


In [166]:
#  combine z and t on a plot
z_t = go.Figure()

z_t.add_trace(go.Scatter(
    x= values_flatten,
    y= pdf_values,
    name='z - distribution',
    mode='lines'
))

z_t.add_trace(go.Scatter(
    x= values_t_flatten,
    y= pdf_values,
    name='t - distribution',
    mode='lines'
))
z_t.update_layout({'title':'Compare z and t distributions'})
z_t.show()

## Confidence Intervals
- to infer results from a sample to be used for another population. If a study is done with sample of subjects we want others to apply those results to their own sample population
- a study, collect 100 cholesterol values and show the mean cholesterol values for our 100 participants as 7.4, express a range of values around this mean. This confidence interval can be used to guess at what the *real* population mean is. Usual CI = 95%
- (1 - *alpha*) = 0.95


In [176]:
# n= 60, std=2, calculate the CI = 95%
confidence_level = stats.norm.ppf(0.975)*2 / np.sqrt(60)
print('confidence level: ', confidence_level)

# subtract the mean to get the lower bound, add to the mean for upper bound
# study cholesterol mean = 7.4
study_chol_mean = 7.4
lower_CI = study_chol_mean - confidence_level
print(lower_CI)
higher_CI = study_chol_mean + confidence_level
print(higher_CI)

#  state the average found in study
findings = "The average cholesterol level was 7.4 (95% CI [6.9 - 7.9])"
print(f'Results: {findings}')

confidence level:  0.506060524752664
6.893939475247336
7.9060605247526645
Results: The average cholesterol level was 7.4 (95% CI [6.9 - 7.9])


new small study, n= 60, 59 degrees of freedom

In [179]:
confidence_level = stats.t.ppf(0.975, 59) * 2 / np.sqrt(60)
print(confidence_level)
lower_CI = study_chol_mean - confidence_level
print('low: ',lower_CI)
higher_CI = study_chol_mean + confidence_level
print('high: ',higher_CI)

0.5166547847430499
low:  6.88334521525695
high:  7.91665478474305
